spring.application.name=crud
#Update the database schema based on the entities create-drop / update
spring.jpa.hibernate.ddl-auto = update
#create database if not exists mysql true spring boot
spring.datasource.url=jdbc:mysql://localhost:3306/crud?createDatabaseIfNotExist=true
#DB User
spring.datasource.username=root
#DB password
spring.datasource.password=laboratorio
